#!/bin/bash

RUNDIR=`dirname $0`

VERSION=`cat $RUNDIR/gcc_min_version | sed 's/\(.*\)\.\(.*\)\..*/\1 \2/'`
#get the first and second numbers out
MAJOR=${VERSION%% *}
MINOR=${VERSION#* }

sed -e "s/REQUIRED_MAJOR/$MAJOR/" -e "s/REQUIRED_MINOR/$MINOR/" < \
  $RUNDIR/version.cpp.in
