#!/bin/bash

INSTALL_ROOT=$1
ENV_ROOT=$2
BUILDDIR=$3

cd $BUILDDIR

export PATH=$INSTALL_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$INSTALL_ROOT/lib:$ENV_ROOT/lib/:$ENV_ROOT/lib64/:$LD_LIBRARY_PATH

ctest -D Nightly
